[general]
import = ["~/.config/alacritty/dracula.toml"]
live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 15.0

[font.bold]
family = "JetBrainsMonoNL Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMonoNL Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMonoNL Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMonoNL Nerd Font"
style = "Medium"

# tmux: enter copy mode
[[keyboard.bindings]]
chars = "\u0002["
key = "Y"
mods = "Command"

# tmux: enter copy mode and search up
[[keyboard.bindings]]
chars = "\u0002[?"
key = "Slash"
mods = "Command"

# tmux: command prompt
[[keyboard.bindings]]
chars = "\u0002:"
key = "Semicolon"
mods = "Command"

# tmux: sesh session picker with fuzzy finding
[[keyboard.bindings]]
chars = "\u0002T"
key = "K"
mods = "Command"

# tmux: switch to last session (via sesh)
[[keyboard.bindings]]
chars = "\u0002L"
key = "L"
mods = "Command|Shift"

# tmux: create new window
[[keyboard.bindings]]
chars = "\u0002c"
key = "T"
mods = "Command"

# tmux: close current window
[[keyboard.bindings]]
chars = "\u0002&"
key = "W"
mods = "Command"

# tmux: previous window
[[keyboard.bindings]]
chars = "\u0002p"
key = 33               # left bracket [
mods = "Command|Shift"

# tmux: next window
[[keyboard.bindings]]
chars = "\u0002n"
key = 30               # right bracket ]
mods = "Command|Shift"

# tmux: jump between last used windows
[[keyboard.bindings]]
chars = "\u0002l"
key = "L"
mods = "Command"

# tmux: swap window prompt
[[keyboard.bindings]]
chars = "\u0002\u0053"
key = "S"
mods = "Command|Shift"

# tmux: switch to window 1
[[keyboard.bindings]]
chars = "\u00021"
key = "Key1"
mods = "Command"

# tmux: switch to window 2
[[keyboard.bindings]]
chars = "\u00022"
key = "Key2"
mods = "Command"

# tmux: switch to window 3
[[keyboard.bindings]]
chars = "\u00023"
key = "Key3"
mods = "Command"

# tmux: switch to window 4
[[keyboard.bindings]]
chars = "\u00024"
key = "Key4"
mods = "Command"

# tmux: switch to window 5
[[keyboard.bindings]]
chars = "\u00025"
key = "Key5"
mods = "Command"

# tmux: switch to window 6
[[keyboard.bindings]]
chars = "\u00026"
key = "Key6"
mods = "Command"

# tmux: switch to window 7
[[keyboard.bindings]]
chars = "\u00027"
key = "Key7"
mods = "Command"

# tmux: switch to window 8
[[keyboard.bindings]]
chars = "\u00028"
key = "Key8"
mods = "Command"

# tmux: switch to window 9
[[keyboard.bindings]]
chars = "\u00029"
key = "Key9"
mods = "Command"

# tmux: split window vertically
[[keyboard.bindings]]
chars = "\u0002%"
key = 42               # backslash \
mods = "Command|Shift"

# tmux: split window horizontally
[[keyboard.bindings]]
chars = "\u0002\""
key = 27               # minus -
mods = "Command|Shift"

# tmux: kill current pane
[[keyboard.bindings]]
chars = "\u0002x"
key = "X"
mods = "Command|Shift"

# tmux: switch to next pane layout
[[keyboard.bindings]]
chars = "\u0002 "
key = "C"
mods = "Command|Shift"

# tmux: zoom/unzoom current pane
[[keyboard.bindings]]
chars = "\u0002z"
key = "Z"
mods = "Command|Shift"

# tmux: expand pane into new window
[[keyboard.bindings]]
chars = "\u0002!"
key = "E"
mods = "Command|Shift"

# tmux: fixing ^H to work with tmux panes
# https://github.com/christoomey/vim-tmux-navigator/issues/421#issuecomment-2613993818
[[keyboard.bindings]]
chars = "\u001B[104;5u"
key = "H"
mods = "Control"

# zsh: clear screen
[[keyboard.bindings]]
# map ctrl+alt+l to send a unique esc sequence (\u001b\u000c) to the shell
# this is needed because many terminals don't distinguish alt from other modifiers by default
chars = "\u001b\u000c"
key = "L"
mods = "Control|Alt"

[terminal]
osc52 = "OnlyCopy"

[window]
decorations = "buttonless"

[window.padding]
x = 10
y = 10
